// Mock data for development and testing
export const mockContents = [
  {
    id: '1',
    title: 'Introdução à Inteligência Artificial',
    description: 'Conceitos fundamentais de IA, história e aplicações práticas no mundo moderno.',
    type: 'video' as const,
    difficulty: 'iniciante' as const,
    duration: '45min',
    rating: 4.8,
    thumbnail_url: null,
    content_url: null,
    subject: 'Inteligência Artificial',
    tags: ['IA', 'fundamentos', 'iniciante'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '2',
    title: 'Estruturas de Dados em Python',
    description: 'Aprenda listas, tuplas, dicionários e sets com exemplos práticos e exercícios.',
    type: 'article' as const,
    difficulty: 'intermediário' as const,
    duration: '30min',
    rating: 4.6,
    thumbnail_url: null,
    content_url: null,
    subject: 'Programação',
    tags: ['Python', 'estruturas de dados'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '3',
    title: 'Algoritmos de Machine Learning',
    description: 'Guia completo sobre algoritmos de ML: regressão, classificação e clustering.',
    type: 'pdf' as const,
    difficulty: 'avançado' as const,
    duration: '2h',
    rating: 4.9,
    thumbnail_url: null,
    content_url: null,
    subject: 'Machine Learning',
    tags: ['ML', 'algoritmos', 'avançado'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '4',
    title: 'Desenvolvimento Web com React',
    description: 'Curso prático de React desde o básico até conceitos avançados como hooks e context.',
    type: 'video' as const,
    difficulty: 'intermediário' as const,
    duration: '3h 20min',
    rating: 4.7,
    thumbnail_url: null,
    content_url: null,
    subject: 'Desenvolvimento Web',
    tags: ['React', 'web', 'frontend'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '5',
    title: 'Banco de Dados SQL',
    description: 'Fundamentos de SQL, consultas avançadas e design de banco de dados relacionais.',
    type: 'article' as const,
    difficulty: 'iniciante' as const,
    duration: '1h 15min',
    rating: 4.5,
    thumbnail_url: null,
    content_url: null,
    subject: 'Banco de Dados',
    tags: ['SQL', 'database', 'backend'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '6',
    title: 'Deep Learning e Redes Neurais',
    description: 'Conceitos avançados de deep learning, CNN, RNN e transformers.',
    type: 'pdf' as const,
    difficulty: 'avançado' as const,
    duration: '4h',
    rating: 4.8,
    thumbnail_url: null,
    content_url: null,
    subject: 'Deep Learning',
    tags: ['deep learning', 'neural networks', 'IA'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '7',
    title: 'Python para Iniciantes',
    description: 'Aprenda Python do zero: sintaxe, variáveis, loops e funções.',
    type: 'video' as const,
    difficulty: 'iniciante' as const,
    duration: '2h',
    rating: 4.8,
    thumbnail_url: null,
    content_url: null,
    subject: 'Programação',
    tags: ['Python', 'iniciante', 'programação'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '8',
    title: 'Programação Orientada a Objetos',
    description: 'Classes, herança, polimorfismo e encapsulamento em Python.',
    type: 'video' as const,
    difficulty: 'intermediário' as const,
    duration: '2h 30min',
    rating: 4.9,
    thumbnail_url: null,
    content_url: null,
    subject: 'Programação',
    tags: ['POO', 'Python', 'orientação a objetos'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '9',
    title: 'Docker: Containers na Prática',
    description: 'Containerize suas aplicações com Docker.',
    type: 'video' as const,
    difficulty: 'iniciante' as const,
    duration: '2h 10min',
    rating: 4.8,
    thumbnail_url: null,
    content_url: null,
    subject: 'DevOps',
    tags: ['Docker', 'containers', 'DevOps'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '10',
    title: 'Quiz: Fundamentos de IA',
    description: 'Teste seus conhecimentos sobre os conceitos básicos de Inteligência Artificial.',
    type: 'quiz' as const,
    difficulty: 'iniciante' as const,
    duration: '15min',
    rating: 4.7,
    thumbnail_url: null,
    content_url: null,
    subject: 'Inteligência Artificial',
    tags: ['quiz', 'IA', 'avaliação'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '11',
    title: 'Redes Neurais Artificiais',
    description: 'Compreenda o funcionamento de redes neurais e sua aplicação em problemas reais.',
    type: 'article' as const,
    difficulty: 'intermediário' as const,
    duration: '1h 30min',
    rating: 4.7,
    thumbnail_url: null,
    content_url: null,
    subject: 'Inteligência Artificial',
    tags: ['IA', 'neural networks', 'deep learning'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '12',
    title: 'Processamento de Linguagem Natural',
    description: 'Aprenda técnicas de NLP para análise e geração de texto.',
    type: 'video' as const,
    difficulty: 'avançado' as const,
    duration: '2h 15min',
    rating: 4.9,
    thumbnail_url: null,
    content_url: null,
    subject: 'Inteligência Artificial',
    tags: ['NLP', 'IA', 'text processing'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '13',
    title: 'HTML5 e CSS3 Essenciais',
    description: 'Fundamentos de desenvolvimento web: estrutura e estilização.',
    type: 'video' as const,
    difficulty: 'iniciante' as const,
    duration: '2h 30min',
    rating: 4.7,
    thumbnail_url: null,
    content_url: null,
    subject: 'Desenvolvimento Web',
    tags: ['HTML', 'CSS', 'web'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '14',
    title: 'JavaScript Moderno (ES6+)',
    description: 'Arrow functions, destructuring, promises e async/await.',
    type: 'article' as const,
    difficulty: 'intermediário' as const,
    duration: '2h 15min',
    rating: 4.8,
    thumbnail_url: null,
    content_url: null,
    subject: 'Desenvolvimento Web',
    tags: ['JavaScript', 'ES6', 'frontend'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '15',
    title: 'PostgreSQL Avançado',
    description: 'Otimização de queries, índices e performance tuning.',
    type: 'article' as const,
    difficulty: 'avançado' as const,
    duration: '2h 30min',
    rating: 4.9,
    thumbnail_url: null,
    content_url: null,
    subject: 'Banco de Dados',
    tags: ['PostgreSQL', 'otimização', 'avançado'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];
