// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftpdhzcyfcuirvnfzobb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0cGRoemN5ZmN1aXJ2bmZ6b2JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NDE0NDIsImV4cCI6MjA3NDQxNzQ0Mn0.n6DuZvjOJlj84d8p1cW86zeZ6TPBu8U35QtGgaTrQvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});